### ISSUE TITLE
Error: getConfigurationForKey() excpects a string

### ISSUE THREAD

**Issue by janstieler** [omz13/kirby3-feeds#2]
Hi,
thank you for this helpfull plugin!
If I try to show the firehose atom through `feeds/atom/` I get shown teh debugger with the error `Return value of omz13\Feeds::getConfigurationForKey() must be of the type string, array returned`. In the config file I have used `'omz13.feeds.firehose' => ['blogarticles'],` blogarticle are my collection.
Have you an Idea whats wrong?

Cheers

**Comment by omz13** [comment]
`firehose` is a string not an array.
In the docs, the description is correct, but the examples are wrong (my bad!).
Try: `omz13.feeds.firehose' => 'blogarticles'`

**Comment by janstieler** [comment]
Thanks! Now it works perfect.
